modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/HaloOfBlocks/yugogun/issues"

[[mods]]
    modId="yugogun"
    version="0.8.0"
    displayName="Additional Guns"
    updateJSONURL="https://raw.githubusercontent.com/HaloOfBlocks/VersionChecker/main/yugogun/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/additional-guns"
    authors="Halo of Blocks Team: Autovw, CasualNoLifer"
    credits="Mr. Pineapple, ThatAvocado_Boi, JamesTheMaker, JaMychal1, SirSpark1313, VIKTORWOOD, Mercuriousity, Igggosha, WitherFlint343, Joel McCassidy, GreenFox011, Lieutenant Howitzer, Hobbeswyn"
    description="Additional Guns focuses on implementing assets made by the community alongside special features that are not included in the base mod to enhance the Gun Mod experience. - To contribute, head over to the GitHub or simply join discord.gg/47c9FG7fdW and let us know!"

[[dependencies.yugogun]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.yugogun]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[modproperties.yugogun]
    catalogueItemIcon="yugogun:ace_of_spades"
    configuredBackground="minecraft:textures/block/stripped_birch_log.png"